### ISSUE TITLE
Fixed number of platforms ( for no reason)

### ISSUE THREAD

**Issue by Vianpyro** [Vianpyro/NSI-saints-days-game-project#3]
The amount of generated platforms seems fixed (and should not)

**Comment by beatorizu** [comment]
I think that we could replace the logic of drawing 10 platforms by removing the first platform from the left size of the canvas and add new one to the right size of the canvas. And for every frame update the platform position and draw the updated. I could try this issue :slightly_smiling_face:

**Comment by Vianpyro** [comment]
> I think that we could replace the logic of drawing 10 platforms by removing the first platform from the left size of the canvas and add new one to the right size of the canvas. And for every frame update the platform position and draw the updated. I could try this issue 🙂

Thank you I'll try this asap ! :D
